version: "3"
services:
  db:
    image: mysql:5.7
    container_name: testsql2
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: sample_sql
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root